[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200

; ESP32-S3R8
board_build.arduino.memory_type = dio_opi
board_build.flash_mode = dio
board_build.psram_type = opi

; 16MB Flash
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.extra_flags = -DBOARD_HAS_PSRAM

lib_deps =
    lvgl/lvgl@8.4.0
    moononournation/GFX Library for Arduino@1.5.0

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LV_CONF_INCLUDE_SIMPLE
    -I include